name: "Static website deploy homolog"

on: 
  push:
    branches:
      - homolog

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: "Deploy to Netlify"
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
    
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_HOMOLOG }}
        with:
          args: deploy --dir=./build --prod